<?xml version="1.0" encoding="UTF-8"?><testrun name="ItemPedidoTest" project="webpizzaria" tests="4" started="4" failures="1" errors="0" ignored="0">
  <testsuite name="unitarios.ItemPedidoTest" time="0.0">
    <testcase name="testCriarItemPedidoPedidoInvalido" classname="unitarios.ItemPedidoTest" time="0.0"/>
    <testcase name="testCriarItemPedidoPizzaInvalida" classname="unitarios.ItemPedidoTest" time="0.0"/>
    <testcase name="testCriarItemPedido" classname="unitarios.ItemPedidoTest" time="0.0"/>
    <testcase name="testCriarItemPedidoQuantidadeInvalida" classname="unitarios.ItemPedidoTest" time="0.0">
      <failure>java.lang.AssertionError: Expected exception: excecoes.ExcecaoDeItemPedido
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
  </testsuite>
</testrun>
