<?xml version="1.0" encoding="UTF-8"?><testrun name="ClienteTest" project="webpizzaria" tests="20" started="20" failures="1" errors="0" ignored="0">
  <testsuite name="unitarios.ClienteTest" time="0.001">
    <testcase name="testDefinirNome" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testCriarClienteEmailInvalido" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testCriarClienteSenhaInvalido" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testCriarClienteTelefoneInvalido" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testCriarCliente" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testDefinirEnderecoInvalido" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testDefinirId" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testDefinirEmailInvalido" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testRealizarAutenticacaoSenhaCorreta" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testDefinirSenhaInvalida" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testDefinirEndereco" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testCriarClienteNomeInvalido" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testDefinirTelefoneInvalido" classname="unitarios.ClienteTest" time="0.0">
      <failure>java.lang.AssertionError: Expected exception: excecoes.ExcecaoDeCliente
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="testDefinirIdInvalido" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testDefinirNomeInvalido" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testDefinirEmail" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testDefinirSenha" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testDefinirTelefone" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testRealizarAutenticacaoSenhaIncorreta" classname="unitarios.ClienteTest" time="0.0"/>
    <testcase name="testCriarClienteEnderecoInvalido" classname="unitarios.ClienteTest" time="0.0"/>
  </testsuite>
</testrun>
