<?xml version="1.0" encoding="UTF-8"?><testrun name="PedidoTest" project="webpizzaria" tests="17" started="17" failures="1" errors="0" ignored="0">
  <testsuite name="unitarios.PedidoTest" time="0.001">
    <testcase name="testDefinirDataHoraInvalida" classname="unitarios.PedidoTest" time="0.001"/>
    <testcase name="testObterValorTotal" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testIncluirPizzaJaExistente" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testDefinirCliente" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testDefinirId" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testDefinirPagamento" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testDefinirPagamentoInvalido" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testNovoPedidoClienteInvalido" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testDefinirDataHora" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testDefinirItensInvalido" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testDefinirIdInvalido" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testDefinirClienteInvalido" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testObterValorDeTroco" classname="unitarios.PedidoTest" time="0.0">
      <failure>java.lang.AssertionError: expected:&lt;30.0&gt; but was:&lt;0.0&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at unitarios.PedidoTest.testObterValorDeTroco(PedidoTest.java:387)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="testRemoverPizza" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testDefinirItens" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testIncluirPizza" classname="unitarios.PedidoTest" time="0.0"/>
    <testcase name="testNovoPedido" classname="unitarios.PedidoTest" time="0.0"/>
  </testsuite>
</testrun>
