package unitarios;

import static org.junit.Assert.*;

import org.junit.Test;

import dominio.Cliente;
import excecoes.ExcecaoDeCliente;

public class ClienteTest {

	@Test
	public void testCriarCliente(){
		String telefone = "2652 7700";
		String email = "oi@oi.com";
		String senha = "1234";
		String nome = "Joao da Silva";
		String endereco = "Avenida Nilo Pecanha";
		
		try {
			Cliente cliente = Cliente.criarCliente(telefone, nome, email, senha, endereco);
			
			assertNotNull(cliente);
			
			/*Valida os dados inseridos*/
			assertEquals(telefone, cliente.obterTelefone());
			assertEquals(email, cliente.obterEmail());
			assertEquals(senha, cliente.obterSenha());
			assertEquals(nome, cliente.obterNome());
			assertEquals(endereco, cliente.obterEndereco());
			
		} catch (ExcecaoDeCliente e) {
			e.printStackTrace();
		}
	}
	
	
	public void testRealizarAutenticacao(String senha) throws ExcecaoDeCliente{
		Boolean senhaCorreta = this.senha.equals(senha);
		
		if(senhaCorreta == false)
			throw new ExcecaoDeCliente("cliente.realizar_autenticacao.senha_invalida");
	}
}
